# Generated by Django 3.2.5 on 2021-11-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20211104_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
