# Generated by Django 3.2.5 on 2021-11-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_categories_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='review/')),
                ('review', models.TextField()),
            ],
        ),
    ]
