# Generated by Django 3.2.5 on 2021-11-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
